### ISSUE TITLE
production docker COPY multistage typo (from staging)

### ISSUE THREAD

**Issue by ashwalk33r** [TusharRoy23/food-app-nestjs#10]
food-app-nestjs/dockerfiles/Dockerfile-prod
https://github.com/TusharRoy23/food-app-nestjs/blob/master/dockerfiles/Dockerfile-prod#L20

has
```
# Stage 2
FROM node:18-alpine as productionBuild
```

but is using
```
COPY --from=stagingBuild /usr/src/app/node_modules ./node_modules
COPY --from=stagingBuild /usr/src/app/dist ./dist
```

shouldnt it be instead
```
COPY --from=productionBuild /usr/src/app/node_modules ./node_modules
COPY --from=productionBuild /usr/src/app/dist ./dist
```

Cant open PR (no permissions) so leaving details here

**Comment by TusharRoy23** [comment]
Thanks for finding out. But I think that would be `--from=productionBuild`.

**Comment by ashwalk33r** [comment]
haha yes, I did the typo mistake myself, sure I wanted to say `productionBuild`

**Comment by ashwalk33r** [comment]
I see you've fixed it in https://github.com/TusharRoy23/food-app-nestjs/commit/dd9f60656379a38fdb5072d7f207002942f9a1da so I will close this issue.
